### PR TITLE
Fixes compiler warning and some other things

### LINKED ISSUE #9: libcluon is using an old version of the stringtoolbox library
I would hope that libcluon could update to use the latest v0.0.4 of the stringtoolbox library. It would simply be fantastic!

### PR DESCRIPTION
**Pull request by olbender**
Fixes #9, and a no-return warning regression from peglib

### CODE REVIEW

**Comment by olbender** [comment]
Fixed a bug where 'id' and 'default' could not co-exists from PEG, resulting in ids being set to auto-counter instead of real id. This prevented dynamically created messages (where 'id' and 'default' are always added by default). In turn this resulted in visitors not working when there was a gap in the id ranges (e.g. OpenDLV message 19).

**Review by chrberger — COMMENTED** [review]
cherry-picked 9195939cf00eb09a1919e01cf04667b6a6a10674/MessageParser.cpp to integrate bugfix.

Updated test-suites to restore old test cases and added new test cases with @olbender's changes to the tests.

**Review by chrberger — COMMENTED** [review]
Rejecting change as documentation is correct (sources live in sub-tree "libcluon").

**Comment by chrberger** [comment]
Adding @olbender's parser fix https://github.com/chrberger/libcluon/commit/803b4589c44edcec76f0158ca01f03341383ab31 into https://github.com/chrberger/libcluon/pull/19/commits
Adding @olbender's stringtoolbox fix https://github.com/chrberger/libcluon/commit/f29f351692a7b5576a2c51f729d5f89cdc2706f1 into https://github.com/chrberger/libcluon/pull/19/commits

**Pull request merged**
